; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
resetISRC:
	; >>>>> Line:	4
	; >>>>> void resetISRC(void) { 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	5
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
	ALIGN	2
L_myinth_4:
	DW	0
L_myinth_5:
	DB	"TICK ",0
	ALIGN	2
tickISRC:
	; >>>>> Line:	8
	; >>>>> void tickISRC(void) { 
	jmp	L_myinth_6
L_myinth_7:
	; >>>>> Line:	10
	; >>>>> tickCount++; 
	inc	word [L_myinth_4]
	; >>>>> Line:	11
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	12
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_5
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	13
	; >>>>> printInt(tickCount); 
	push	word [L_myinth_4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_myinth_6:
	push	bp
	mov	bp, sp
	jmp	L_myinth_7
L_myinth_12:
	DB	") IGNORED",0
L_myinth_11:
	DB	"KEYPRESS (",0
L_myinth_10:
	DB	"DELAY COMPLETE",0
L_myinth_9:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
kbISRC:
	; >>>>> Line:	17
	; >>>>> void kbISRC(void) { 
	jmp	L_myinth_13
L_myinth_14:
	; >>>>> Line:	19
	; >>>>> if(KeyBuffer == 100){ 
	cmp	word [KeyBuffer], 100
	jne	L_myinth_15
	; >>>>> Line:	21
	; >>>>> printNewLine(); 
	mov	word [bp-2], 0
	; >>>>> Line:	21
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	22
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_myinth_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	23
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	24
	; >>>>> while(i < 5000) { 
	jmp	L_myinth_17
L_myinth_16:
	; >>>>> Line:	25
	; >>>>> i++; 
	inc	word [bp-2]
L_myinth_17:
	cmp	word [bp-2], 5000
	jl	L_myinth_16
L_myinth_18:
	; >>>>> Line:	27
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	28
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	29
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_myinth_19
L_myinth_15:
	; >>>>> Line:	31
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	32
	; >>>>> printString("KEYPRESS 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> printChar(KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	34
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_myinth_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	35
	; >>>>> printNewLine(); 
	call	printNewLine
L_myinth_19:
	mov	sp, bp
	pop	bp
	ret
L_myinth_13:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_14
