; Generated by c86 (BYU-NASM) 5.1 (beta) from simptris_inth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
gameOverISRC:
	; >>>>> Line:	3
	; >>>>> void gameOverISRC(void) { 
	jmp	L_simptris_inth_1
L_simptris_inth_2:
	; >>>>> Line:	5
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_simptris_inth_1:
	push	bp
	mov	bp, sp
	jmp	L_simptris_inth_2
	ALIGN	2
newPeiceISRC:
	; >>>>> Line:	7
	; >>>>> void newPeiceISRC(void) { 
	jmp	L_simptris_inth_4
L_simptris_inth_5:
	; >>>>> Line:	9
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_simptris_inth_4:
	push	bp
	mov	bp, sp
	jmp	L_simptris_inth_5
	ALIGN	2
receivedCommandISRC:
	; >>>>> Line:	11
	; >>>>> void receivedCommandISRC(void) { 
	jmp	L_simptris_inth_7
L_simptris_inth_8:
	; >>>>> Line:	13
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_simptris_inth_7:
	push	bp
	mov	bp, sp
	jmp	L_simptris_inth_8
	ALIGN	2
touchdownISRC:
	; >>>>> Line:	15
	; >>>>> void touchdownISRC(void) { 
	jmp	L_simptris_inth_10
L_simptris_inth_11:
	; >>>>> Line:	17
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_simptris_inth_10:
	push	bp
	mov	bp, sp
	jmp	L_simptris_inth_11
	ALIGN	2
lineclearISRC:
	; >>>>> Line:	19
	; >>>>> void lineclearISRC(void) { 
	jmp	L_simptris_inth_13
L_simptris_inth_14:
	; >>>>> Line:	21
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_simptris_inth_13:
	push	bp
	mov	bp, sp
	jmp	L_simptris_inth_14
