; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_myinth_1:
	DW	0
L_myinth_2:
	DW	0
YKQ:
	TIMES	2 db 0
queue:
	TIMES	2 db 0
msg:
	TIMES	2 db 0
MsgQPtr:
	TIMES	2 db 0
